// File generated by hand from the real android/app/google-services.json for
// this project (messengerclone-d7f43), matching the FlutterFire CLI's
// standard output shape. Regenerate with `flutterfire configure` if the
// Firebase project ever changes or an iOS/web app is added.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this project currently only targets Android. Run '
        '`flutterfire configure` after adding a web Firebase app.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'this project currently only targets Android. Run '
          '`flutterfire configure` after adding an iOS Firebase app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Real values pulled directly from android/app/google-services.json:
  //   apiKey            <- client[0].api_key[0].current_key
  //   appId             <- client[0].client_info.mobilesdk_app_id
  //   messagingSenderId <- project_info.project_number
  //   projectId         <- project_info.project_id
  //   storageBucket     <- project_info.storage_bucket
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8ZGcCdBOFHuox7f5ox1nLFYMxVEtu0A',
    appId: '1:260839823539:android:4fff8938f83ce00f7bf8c6',
    messagingSenderId: '260839823539',
    projectId: 'messengerclone-d7f43',
    storageBucket: 'messengerclone-d7f43.firebasestorage.app',
  );
}
