
std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Category\": \"Rifle\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFF69B4FF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"                                                 
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFF69B4FF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFF69B4FF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         
                         "        \"itemId\": 101010,\n"
                         "        \"itemClass\": \"BP_Rifle_G36_Wrapper_C_1\",\n"
                         "        \"itemName\": \"G36C\",\n"
                         "        \"itemTextColor\": \"0xFF0000FF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"First Aid Kit\",\n"
                         "        \"itemTextColor\": \"0xFF1AFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601006,\n"
                         "        \"itemClass\": \"FirstAidbox_Pickup_C_1\",\n"
                         "        \"itemName\": \"Med Kit\",\n"
                         "        \"itemTextColor\": \"0xFF1AFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"    
                         "      },\n"
                         "      {\n" 
                         "        \"itemId\": 502003,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv3_C_1\",\n"
                         "        \"itemName\": \"Spetsnaz Helmet (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n" 
                         "      {\n"
                         "        \"itemId\": 503003,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv3_C_1\",\n"
                         "        \"itemName\": \"Military Vest (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         
"      },\n"
"      {\n"
"        \"itemId\": 204011,\n"
"        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
"        \"itemName\": \"Extended Mag\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204013,\n"
"        \"itemClass\": \"BP_DJ_Large_EQ_Pickup_C_1\",\n"
"        \"itemName\": \"Extended Quick Mag\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  }\n"
"]";




